Adjust workflow to work with multiple pages (#1)
* adjust workflow to fetch all pages

diff --git a/.github/workflows/RequestWagoData.yml b/.github/workflows/RequestWagoData.yml
--- a/.github/workflows/RequestWagoData.yml
+++ b/.github/workflows/RequestWagoData.yml
@@ -19,7 +19,43 @@ jobs:
       - run: CrossOriginStuff/ConvertWaList.sh    
       - name: createList
         id: createList
-        run: curl -s 'https://data.wago.io/search/es?q=User%3A%22Jodsderechte%22&mode=wow&page=0&sort=' | jq -cr '"content=\([.hits[].id])"' >> "$GITHUB_OUTPUT"
+        run: |
+          url="https://data.wago.io/search/es?q=User%3A%22Jodsderechte%22&mode=wow&"
+          page_size=25
+          
+          # Get total number of results
+          total_results=$(curl -s "$url&page=0" | jq '.total')
+
+          # If total_results is empty, abort
+          if [ -z "$total_results" ]; then
+            echo "Error: Total results not found or invalid response"
+            exit 1
+          fi
+
+          # Calculate total pages
+          total_pages=$(( (total_results + page_size - 1) / page_size )) # This rounds up
+
+          echo "Checking for a total of: $total_pages pages"
+
+          # Initialize empty JSON array to hold the results
+          results="[]"
+
+          # Loop through each page and append the results
+          for ((page=0; page<total_pages; page++)); do
+            echo "Checking page: $page with url ${url}page=$page"
+            page_results=$(curl -s "${url}page=$page" | jq -c '[.hits[].id]')
+            # Merge the page results into the results array
+            results=$(echo "$results" | jq -s 'add + '"$page_results")
+          done
+
+          # Filter out duplicates and make the list unique
+          unique_results=$(echo "$results" | jq 'unique')
+
+          # Debugging: Output the raw JSON to make sure it's correct
+          echo "Unique results: $unique_results"
+
+          # Set the unique results as an environment variable
+          echo "content=$(echo "$unique_results" | jq -cr .)" >> "$GITHUB_OUTPUT"
       - name: commit results
         run: | 
             git config --local user.name "WagoDataRequest"
